name: Pull Request Pipeline

on: 
  pull_request:
    types: [opened, edited]

defaults:
  run:
    shell: bash -l {0}

jobs:
  job:
    name: Pull Request Pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          lfs: true

    - name: Checkout LFS objects
      run: git lfs pull
    
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
      
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: dochub-example
        environment-file: environment.yml
        python-version: 3.8
        auto-activate-base: false

    - run: |
        conda info
        conda list

    - name: Validate the documents
      run: |
        echo "validating"

    - name: Build the documents
      run: |
        mkdir build
        jupyter nbconvert --to=html --output-dir=build docs/*.ipynb

    - uses: actions/upload-artifact@v2
      with:
        name: docs-html
        path: build/*