on: push
  # pull_request:
  #   types: [opened, edited]

jobs:
  job:
    name: Pull Request Pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
      
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment.yml --name base

    - name: Validate the documents
      run: |
        echo "validating"

    - name: Build the documents
      run: |
        mkdir build
        jupyter nbconvert --to=html --output-dir=build docs/*.ipynb

    - uses: actions/upload-artifact@v2
      with:
        name: docs-html
        path: build/*

    - name: Get artifact url
      run: |
        RESPONSE=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/maxb2/dichub-example/actions/runs/{{ github.run_id }}/artifacts)
        echo "$RESPONSE"


    # - name: comment PR
    #         uses: unsplash/comment-on-pr@master
    #         env:
    #           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #         with:
    #           msg: "Check out this message!"
    #           check_for_duplicate_msg: false  # OPTIONAL 
